---
- name: Create influxdb2 directory
  file:
    path: "/etc/influxdb2"
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Copy configuration file into a config dir
  template:
    src: "templates/influxdb.conf.j2"
    dest: "/etc/influxdb2/influxdb.conf"
    owner: root
    group: root
    mode: "644"

# - name: Generate a Self Signed OpenSSL certificate
#   ansible.builtin.command: |
#     openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/ssl/influxdb-selfsigned.key -out /etc/ssl/influxdb-selfsigned.crt -days 365

  
- name: Give influxdb group access to /etc/ssl certificates
  ansible.builtin.file:
    path: "/etc/ssl/influxdb-selfsigned.{{ item }}"
    owner: root
    group: root
    mode: "644"
  loop:
    - key
    - crt

- name: Start influxdb container
  community.docker.docker_container:
    name: influxdb
    image: influxdb:2.7
    restart_policy: always
    ports:
      - "8086:8086"
    # command: /bin/bash -c "chmod 644 /etc/ssl/influxdb-selfsigned.{crt,key}; influxd --tls-key /etc/ssl/influxdb-selfsigned.key --tls-cert /etc/ssl/influxdb-selfsigned.crt"
    command: influxd
    env:
      # TODO
      DOCKER_INFLUXDB_INIT_MODE=setup
      DOCKER_INFLUXDB_INIT_USERNAME=my-user
      DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      DOCKER_INFLUXDB_INIT_ORG=my-org
      DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      DOCKER_INFLUXDB_INIT_RETENTION=1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - "/etc/ssl:/etc/ssl:ro"
      - "/etc/influxdb:/etc/influxdb"
      - "/var/lib/influxdb2:/var/lib/influxdb2"

- name: Create telegraf directory
  file:
    path: "/etc/telegraf"
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Copy telegraf configuration file into a config dir
  template:
    src: "files/telegraf.conf"
    dest: "/etc/telegraf/telegraf.conf"
    owner: root
    group: root
    mode: "644"

- name: Start influxdb container
  community.docker.docker_container:
    name: telegraf
    image: telegraf:1.28.2
    restart_policy: always
    volumes:
      - "/etc/telegraf:/etc/telegraf"
