---
- name: ufw outgoing allow all
  community.general.ufw:
    state: enabled
    direction: outgoing
    policy: allow

- name: Allow OpenSSH by default
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: ufw incoming deny all expect OpenSSH
  community.general.ufw:
    state: enabled
    direction: incoming
    policy: deny

- name: ufw allow https
  community.general.ufw:
    rule: allow
    name: https

- name: ufw allow influxdb port
  community.general.ufw:
    rule: allow
    port: '8086'
